baseURL = "https://yuya-0928.github.io/yuniyuni.com/"
languageCode = "utf8-mb4"
title = "yuni's blog"
theme = "github-style"
googleAnalytics = "#"
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "docs"
canonifyurls = true

[params]
  author = "yuni"
  description = "In solitude, where we are least alone."
  github = "https://github.com/yuya-0928"
  facebook = "#"
  twitter = "hirattchi0928"
  linkedin = "#"
  instagram = "#"
  tumblr = "#"
  email = "#"
  url = "https://yuya-0928.github.io/yuniyuni.com/"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "Japan"

  [[params.links]]
    title = "Link"
    href = "https://github.com/yuya-0928"
  [[params.links]]
    title = "Link2"
    href = "https://yuya-0928.github.io/yuniyuni.com/"
    icon = "https://yuya-0928.github.io/yuniyuni.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
